sudo: required

language: ruby

services:
  - docker

before_install:
- mkdir -p themes && rm -rf themes/*
- git clone https://github.com/tapanchandra/hugo-theme-m10x themes/m10x
- rm -rf themes/m10x/.git
- mkdir -p docs && rm -rf docs/*

script:
- docker run --rm -it -v $(pwd):/src -u hugo jguyomard/hugo-builder hugo
- ls
- ls docs

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  
#   local-dir: /docs/
#   on:
#     branch: master