sudo: required

language: generic

services:
  - docker

before_install:
- mkdir -p themes && rm -rf themes/*
- git clone https://github.com/tapanchandra/hugo-theme-m10x themes/m10x
- rm -rf themes/m10x/.git
- mkdir -p docs && rm -rf docs/*

script:
- docker run --rm -it -v $(pwd):/src jguyomard/hugo-builder hugo
- ls public
- mkdir -p public
- sudo echo "tapanchandra.com" > public/CNAME
- ls public

deploy:
  provider: pages  
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  local-dir: public
  on:
    branch: master