baseURL = "https://www.tapanchandra.com"
languageCode = "en-us"
title = "Rusty Coder's Blog"
theme = "m10x"

[params]
  author = "Tapan Chandra"
  description = "Welcome to the personal site of Tapan Nallan."
  [[params.social]]
    name = "github"
    url = "https://github.com/tapanchandra"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/codingjack_"